services:
  db:
    env_file: !override
      - .env.development

  app:
    command:
      [
        "sh",
        "-c",
        "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level info"
      ]
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./scripts:/app/scripts
    environment:
      - ENV=development
    env_file: !override
      - .env.development
