"""rename to title

Revision ID: 090b69375243
Revises: 2600a6330c7d
Create Date: 2026-10-08 06:11:37.944972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090b69375243'
down_revision: Union[str, None] = '2600a6330c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topics', 'name', new_column_name='title')
    op.drop_constraint('topics_name_key', 'topics', type_='unique')
    op.create_unique_constraint('topics_title_key', 'topics', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('topics_title_key', 'topics', type_='unique')
    op.create_unique_constraint('topics_name_key', 'topics', ['name'])
    op.alter_column('topics', 'title', new_column_name='name')
    # ### end Alembic commands ###
